version: '3.3'
services:
  holigo-product-service:
    image: holigo/holigo-product-service:1.1.2
    ports:
      - 8084:8084
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-product-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-product-service"}}'
    deploy:
      replicas: 1
  holigo-transaction-service:
    image: holigo/holigo-transaction-service:1.1.0
    ports:
      - 8089:8089
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-transaction-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-transaction-service"}}'
    deploy:
      replicas: 1
#    labels:
#      collect_logs_with_filebeat: "true"
#      decode_log_event_to_json_object: "true"      
